- name: Ensure that sudo is installed
  ansible.builtin.package:
    name: sudo
    state: present

- name: "Allow group to have passwordless sudo: {{ sudo_group }}"
  ansible.builtin.lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%{{ sudo_group }}'
    line: '%{{ sudo_group }} ALL=(ALL) NOPASSWD: ALL'
    validate: '/usr/sbin/visudo -cf %s'
